### ISSUE TITLE
Editing the AvailableCommandsPacket doesn't work with Waterdog

### ISSUE THREAD

**Issue by Wertzui123** [yesdog/Waterdog#103]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.15-SNAPSHOT:a1a01bc:298

**Expected Behavior**
The command description and usage should change as expected, after editing the command data.

**Actual Behavior**
Nothing changes.

**Crashdump, Backtrace or Other Files**

**Describe the bug**
When I edit the command data while listening on a AvailableCommandsPacket, the new data isn't sent to the client. It works on servers without waterdog.

**To Reproduce**
1. Make a plugin which listens on the AvailableCommandsPacket and edits the command descriptions
2. Join the server and type the command to see it's description and usage - it hasn't changed

**Screenshots**

**Server software used:**
PocketMine-MP 3.11.6

**Additional context**

**Comment by Alemiz112** [comment]
You should specify more information. What do you mean by `listens on the AvailableCommandsPacket`? Is the plugin for Waterdog or for PMMP?

**Comment by Alemiz112** [comment]
Actually Waterdog does not catch or work with this packet. It would help if you could provide some example code.

**Comment by Wertzui123** [comment]
For PocketMine, I mean something like

```php
public function onAvailableCommands(DataPacketSendEvent $event){
        if($event->getPacket() instanceof AvailableCommandsPacket) {
            // edit command data
        }
}```

**Comment by Wertzui123** [comment]
I'm sorry, it was caused by another plugin.

**Comment by Alemiz112** [comment]
This should work. It may not work only if the packet contains player's EID. Than it must be included in entity rewrite map in WD and it isn't. If you can confirm that it contains the EID, I can implement rewrite for it. If you cant, I would suggest to to try handle `AvailableCommandsPacket` data in Waterdog and inspect if they are right.
