### ISSUE TITLE
Resource Pack download or apply error

### ISSUE THREAD

**Issue by SeqSEE** [yesdog/Waterdog#106]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.15-SNAPSHOT:188cf2b:unknown

**Expected Behavior**
Client should connect and get the resource pack (since it is already being cached already)

**Actual Behavior**
Client cannot connect to Waterdog proxy with resource pack, although it does get cached, without first restarting after a failure to download/apply error.

**Crashdump, Backtrace or Other Files**
[cryptechcraft_pack.zip](https://github.com/yesdog/Waterdog/files/4513255/cryptechcraft_pack.zip)
Not that I think there is any issue with the pack, just in case it is helpful.

**Describe the bug**
Client cannot join proxy with resource pack without restarting client after error and re-joining even though resource pack is cached.

**To Reproduce**
- Remove any cached local client resource pack that is the one that is on the proxy
- Connect to server (Waterdog) and click Any option other that leave regarding resource packs
- Client gets error, and every time after in this game session of "Encountered a problem while downloading or applying the resource pack"
- Close client completely and the pack shows as cached
- Reconnect to Waterdog, works from cache without prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/15011102/79929344-75927900-8413-11ea-85f1-65c2a1de9e2e.png)

**Server software used:**
NukkitX

**Additional context**

**Comment by Alemiz112** [comment]
Resource packs should be working correctly now.
