### ISSUE TITLE
AdventureSettingsPacket not working properly

### ISSUE THREAD

**Issue by TobiasG-DE** [yesdog/Waterdog#11]
Player::setAllowFlight() used by PocketMine-MP based MCPE Servers is not working properly ( Mostly doesn't work ).

Steps to reproduce the issue:
Connect to a pmmp server via Watchdog and try to use a command which enables flight for your player instance

**Comment by AlexPads** [comment]
I have never had an issue with this...

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/bf285f4825432438bcd7ddfc0333e0faae6ee249
