### ISSUE TITLE
WaterDog Packs (Resource Pack)

### ISSUE THREAD

**Issue by Asadaaaaa** [yesdog/Waterdog#110]
Hello yesdog, i use waterdog in my server. and i use my resource pack (.mcpack) in folder packs of waterdog, if im join to server, i click download and always error. message error is "Ecountered a problem while downloading or applying resource pack.

**Comment by UnknowG** [comment]
To put a resource pack you need to zip and rename it to .mcpack and put it in the "packs" folder ?

**Comment by Alemiz112** [comment]
Resource packs should be working correctly now. Yes, you have to change `.zip` to `.mcpack`.

**Comment by zOmArRD** [comment]
![image](https://user-images.githubusercontent.com/64379283/124011826-6e1f1600-d9ae-11eb-9b22-f3f343c3523b.png)

have problem

**Comment by xxFLORII** [comment]
i think that's the wrong repository.

**Comment by xxFLORII** [comment]
https://github.com/WaterdogPE/WaterdogPE create an issue here
