### ISSUE TITLE
Steadfast support

### ISSUE THREAD

**Issue by DanielllxD** [yesdog/Waterdog#113]
**Version of Waterdog**

The latest.... commit: f3a226f

**Expected Behavior**
Join normally, without getting killed?

**Actual Behavior**
I spawned below bedrock level, instantly, died.

**Crashdump, Backtrace or Other Files**

**Describe the bug**
When I join a steadfast server through Waterdog, players, or, I, spawn below bedrock level, and dies instantly

**To Reproduce**
Create a steadfast server,
Add it to proxy, join through proxy, and watch what happens!

**Screenshots**

**Server software used:**

Steadfast: https://github.com/Hydreon/Steadfast2

**Additional context**
Also, NPCs skins do not show at all, shows the default steve skin, spawn a human npc use any skin other than steve, and if you join from the proxy, you will see steve skin instead.

**Comment by ethaniccc** [comment]
I used Steadfast with Waterdog 2 months ago, with me on 1.12 and my friend on 1.14.

**Comment by colinrgodsey** [comment]
@DanielllxD please reopen this issue if the problem persists. thanks!
