### ISSUE TITLE
Steadfast support

### ISSUE THREAD

**Issue by xZeroMCPE** [yesdog/Waterdog#115]
@DanielllxD please reopen this issue if the problem persists. thanks!

_Originally posted by @colinrgodsey in https://github.com/yesdog/Waterdog/issues/113#issuecomment-643511157_

**Comment by xZeroMCPE** [comment]
@DanielllxD Is the issue still happening?

**Comment by DanielllxD** [comment]
> @DanielllxD Is the issue still happening?

ye just tried it, plus this wouldnt let me make issue tnx for creating it for me

**Comment by TobiasG-DE** [comment]
The Skin issue is odd. I'll have a look into that whenever I have time

**Comment by Alemiz112** [comment]
Waterdog parse skin data correctly. If It wont, It would not work. With next update of WD, we will be able to guarantee this on 99.9%. But WD works fine with PMMP or Nukkit. According to this I would say, Steadfast is the problem.
