### ISSUE TITLE
Spawning into different location of the world

### ISSUE THREAD

**Issue by ItzLightyHD** [yesdog/Waterdog#116]
When i spawn into the lobby 

**Version of Waterdog**
This server is running Waterdog version git:Waterdog-Bootstrap:1.15-SNAPSHOT:1de3ca3:310 by md_5

**Expected Behavior**
When I join into the server, I don't spawn in the actual lobby, but in the void. Then, i need to do /spawn to warp into the actual spawn

**Actual Behavior**
The same as the Expected Behavior

**Crashdump, Backtrace or Other Files**
It looks all normal

**Describe the bug**
I don't know if this is a bug or not.

**To Reproduce**
Use a floating spawn in pocketmine, then join the server trough Waterdog

**Screenshots**
https://cdn.discordapp.com/attachments/706083854418575411/723123250623676526/unknown.png

**Server software used:**
PocketMine 3.13.0 (v.1.14.60)

**Additional context**

**Comment by Alemiz112** [comment]
When player joins the server thought proxy, waterdog sends empty chunks to player. After that player should receive new chunk data from  server. I have heard that similar issue happened with latest release of pmmp only. Could you please test it with older version?

**Comment by ItzLightyHD** [comment]
> When player joins the server thought proxy, waterdog sends empty chunks to player. After that player should receive new chunk data from server. I have heard that similar issue happened with latest release of pmmp only. Could you please test it with older version?

Probably because they deprecated some things, added new ones and changed some things. Probably, if I switch to 3.12.5, Slappers will not work anymore, so i'll try to find another lobby. Thank you for reporting me this problem:
![image](https://user-images.githubusercontent.com/45460688/85023029-76762b80-b174-11ea-9797-825e430e8550.png)
![image](https://user-images.githubusercontent.com/45460688/85023050-7d9d3980-b174-11ea-88ca-c056daabf663.png)
![image](https://user-images.githubusercontent.com/45460688/85023071-855cde00-b174-11ea-9afa-6f43fad61335.png)
![image](https://user-images.githubusercontent.com/45460688/85023089-8c83ec00-b174-11ea-978c-fb3c3d756f2b.png)
![image](https://user-images.githubusercontent.com/45460688/85023101-90b00980-b174-11ea-96ee-d5175a8e3561.png)
