### ISSUE TITLE
Fast transfer (dimension) not working through 2 different IPs

### ISSUE THREAD

**Issue by SamuelPozzobon** [yesdog/Waterdog#117]
Why waterdog can't use dimension changer through two different IPs?

Es.

Lobby: fireworkmc.net 19132
PVP: generalmc.net 19180

(These two IPs are in a different VPS).

Is there a mode to do it?

**Comment by Alemiz112** [comment]
It can use and it does. Do you have different transfer groups on those servers? If yes, than it will use "slow" transfer method.

**Comment by SamuelPozzobon** [comment]
I want to use the dimensional, I send you the config of waterdog, cause when I transfer to pvp server it says could not transfer to a default / fallback server. 

https://hastebin.com/amacuwaxuw.php

**Comment by SamuelPozzobon** [comment]
With this config it doesn't work

**Comment by colinrgodsey** [comment]
Is there any error reported in the waterdog log when you try to transfer?

**Comment by SamuelPozzobon** [comment]
![Screenshot_20200619_202745_com mojang minecraftpe](https://user-images.githubusercontent.com/42522736/85168984-69883380-b26b-11ea-86e0-650a4f8e5f9b.jpg)

**Comment by Alemiz112** [comment]
Yesdog means console log. Anyway this is probably caused because proxy can not communicate with the server or server cant communicate with proxy. Try checking your firewall rules and port forwarding.

**Comment by SamuelPozzobon** [comment]
Oh sorry, there are no errors in the console, but the server is online, all is fine (firewall and port forwarding), it's strange..

**Comment by TobiasG-DE** [comment]
Closed due to inactivity. Can be reopened if necessary
