### ISSUE TITLE
Minecraft 1.16 Official

### ISSUE THREAD

**Issue by brokiem** [yesdog/Waterdog#118]
Does this proxy support Minecraft 1.16 Official? I have added PMMP software
1.16 Support, but when I log in through a proxy, this happen: Server Outdated!

but if no proxy, login successfully

**Comment by Alemiz112** [comment]
Yes. Waterdog does not support mcpe 1.16 at the moment. We are working on it.

**Comment by bali59** [comment]
Iyeeeeeeee

**Comment by irpanXstrome** [comment]
H3h3h3h3h3h3h3,Gua tunggu
