### ISSUE TITLE
Some sites can't reach the server

### ISSUE THREAD

**Issue by Artuto** [yesdog/Waterdog#12]
Some PE listing sites use the PMMP query to show servers online or offline, however, Waterdog does not reply with this type of query to the site, so the site marks it as offline.

I believe the solution to not to break the PC query, to only change the query format or required info in listeners that have raknet set to true.

**Comment by colinrgodsey** [comment]
On the raknet listener, set query_enabled: true. Should work then.

**Comment by Artuto** [comment]
Enabling query on the PE listener did the trick.
