### ISSUE TITLE
Player will be kicked from server (1.16)

### ISSUE THREAD

**Issue by HowToRushDE** [yesdog/Waterdog#127]
![image](https://user-images.githubusercontent.com/38558911/85949852-67a02d80-b959-11ea-96f2-abaa66f21939.png)

i have tried to join with the latest waterdog version, because i will kicked from any server. ( Since 1.16 and servers will not crash )

I have tested it with and without plugins.

![image](https://user-images.githubusercontent.com/38558911/85949900-adf58c80-b959-11ea-9a8f-878d7b8f5bc7.png)

**Comment by RealTriassic** [comment]
I also get issues with players joining using 1.16.

**Comment by GamakCZ** [comment]
Have you disabled xbox auth on pocketmine server?

**Comment by YarkaDev** [comment]
I don't even let me log in, says "outdated server". I have the latest version of Waterdog. How did you get around this problem?

**Comment by Jishrocks** [comment]
Waterdog still isn't for 1.16

**Comment by tuilakhanh** [comment]
Delete your old config and module and try it again

**Comment by TobiasG-DE** [comment]
This issue can only be caused by your configuration. Waterdog itself should fully support 1.16
