### ISSUE TITLE
Which version should I place? 

### ISSUE THREAD

**Issue by InVenoxx** [yesdog/Waterdog#128]
I have a server in 1.16, and I want to use the proxy, but I don't know how to configure it with that version thing to get players from 1.16 in, put it in version '1. 16' but it doesn't work. Any solution or someone to instruct me how to put everything?

**Comment by TobiasG-DE** [comment]
Hey,
you do not need to change the Version anywhere. Just download the newest jar file, linked in the News Channel of our Discord Server, and you should be set, as long as your Serversoftware (PocketMine, Nukkit..) already supports 1.16.

**Comment by InVenoxx** [comment]
Okay, I'm already getting the MOTD, but now when I try to get in it tells me "outdated server", but the pocketmine is the latest version (1.16)

**Comment by CupidonSauce173** [comment]
Download from this link.
https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/4/

**Comment by InVenoxx** [comment]
Oh man thanks
