### ISSUE TITLE
Show real ping of each player

### ISSUE THREAD

**Issue by InVenoxx** [yesdog/Waterdog#129]
Some way that does not ping always on 20 or 41 as if I had good signal?, since I use a score board I would like you to dial the real ping of each player, but with the Waterdog always marks it with good ping

**Comment by Alemiz112** [comment]
Hi, If player is joined thought proxy, ping from `player#getPing()` is actually ping between proxy and server. If you wish to get real ping, use PluginMessages system. You can read more about it in Bungeecord docs.
