### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by UnknowG** [yesdog/Waterdog#131]
How to have a player ip adress without /ip ?

Because we would like to know the player's ip so we can know which account he has, except that since the proxy blocks the ip and it puts us 127.0.0.1 we can't do that like we used to do without the proxy.

**Comment by Alemiz112** [comment]
You can get players ip from `LoginPacket` as attribute in client data. I think it is called `Waterdog_IP`.

**Comment by UnknowG** [comment]
okay and, who to get the server where is the player ?

**Comment by UnknowG** [comment]
in php (PocketMine)

**Comment by Alemiz112** [comment]
You can use Stargate communication system or you can use PluginMessages for it.
For PluginMessages check some examples in WaterdogTools and to message reference look after "bungeecord plugin message" on google.

**Comment by TobiasG-DE** [comment]
Anyways this is a bug tracker and no support forum
