### ISSUE TITLE
Transfer speed slow in 1.16

### ISSUE THREAD

**Issue by mikeygio10** [yesdog/Waterdog#133]
**Version of Waterdog**
 waterdog-bootstrap:1.15snapshoy:4088b94:4

**Expected Behavior**

A fast transfer in 1 or 2s
**Actual Behavior**

A slower and lagger transfer
**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**
 transferring servers

**Screenshots**
 I will down below

**Server software used:**

Pocketmine
**Additional context**

**Comment by mikeygio10** [comment]
https://cdn.discordapp.com/attachments/574244608041811980/729730926107426916/video0.mov

**Comment by EinBexiii** [comment]
I can confirm it.

**Comment by TobiasG-DE** [comment]
This is not an issue caused by Waterdog itself. It is caused by either the connected Downstream Server or any other factor that might cause problems with this like the Internet Connection. We haven't noticed any of those issues in High-Quality Production Servers

**Comment by mikeygio10** [comment]
I know why it does it. If you have old mcpe worlds it does not work and will crash/load slow. But if you create 2 new worlds it will work

**Comment by mikeygio10** [comment]
I think in Minecraft (Bedrock) - Beta 1.16.20.53 it is fixed. But its beta so its not out yet

**Comment by mikeygio10** [comment]
Yup Fixed in 1.16.2
