### ISSUE TITLE
Configuration sample for Nukkit please

### ISSUE THREAD

**Issue by ElStefanos** [yesdog/Waterdog#137]
Title says it all config.yml is really confusing and there aren't any explanations.

**Comment by tuilakhanh** [comment]
@ElStefanos https://hastebin.com/ajoxekuvoz.makefile
here is example

**Comment by Alemiz112** [comment]
For more info about configuration, look [here](https://www.spigotmc.org/wiki/bungeecord-configuration-guide/).

**Comment by TobiasG-DE** [comment]
Just for notice this is not a support forum, this is an issue tracker. If you need Support, join the official Discord Server.
