### ISSUE TITLE
Java 1.7 support

### ISSUE THREAD

**Issue by sachk** [yesdog/Waterdog#14]
Hello, I'm just wondering if you could implement Java Minecraft 1.7.x support. Travertine patches waterfall [here](https://github.com/PaperMC/Travertine/blob/master/Waterfall-Proxy-Patches/0003-1.7.x-Protocol-Patch.patch) to add 1.7 support, so perhaps you could modify that patch to work with Waterdog.

Thanks for making waterdog, it works really well.

**Comment by Artuto** [comment]
If yesdog is implementing 1.7 support please create a toggle for it lol.

**Comment by colinrgodsey** [comment]
Hmmm, this is definitely something I've wondered about. So, waterdog is 1.8 because our raknet lib is 1.8 based. I'm curious to here any use-case/justification for 1.7 thought. I know its tricky to push the JVM "bar" wrt to version, so definitely curious on the use case.

**Comment by sachk** [comment]
I just realised I worded this terribly. I was referring to Java minecraft 1.7.x, not Java 1
7. I don't have any idea why anyone would need that.

**Comment by colinrgodsey** [comment]
Oh damn i see lol. I considered pulling in the travertine patches, because... why not. I can look into that. Originally this was going to be a travertine fork, because it fits the theme of greater protocol support.

**Comment by colinrgodsey** [comment]
added support in https://github.com/yesdog/Waterdog/commit/0c455d59e06a557581be1bbd609264cf994d42db
