### ISSUE TITLE
Scoreboard flickers when you update it

### ISSUE THREAD

**Issue by LucGamesYT** [yesdog/Waterdog#141]
**Version of Waterdog**
 git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4

**Expected Behavior**
No flickers

**Actual Behavior**
Scoreboard flickers when you update it

**To Reproduce**
1. Create a scoreboard
2. Update the scoreboard (PlayerMoveEvent)

**Screenshots**
https://youtu.be/-4BwEnOkpYI

**Server software used:**
Nukkit

**Comment by Alemiz112** [comment]
Duplicate of #62. Closing.

**Comment by LucGamesYT** [comment]
> Duplicate of #62. Closing.

Yeah, I know. Unfortunately, the bug's been in there for almost a year.

**Comment by Alemiz112** [comment]
There are more bugs that can not be solved for some reasons. Opening new issue wont make it fixed.
