### ISSUE TITLE
1.16 support

### ISSUE THREAD

**Issue by YarkaDev** [yesdog/Waterdog#143]
Where can I get Waterdog for 1.16? When I try to connect, I get message "Old server"

**Comment by Alemiz112** [comment]
Hi, we are unable to build 1.16 working jar on official Jenkins server for permission issues. You can use my personal build, [here](https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/).
For feature questions, please visit our Discord server.
