### ISSUE TITLE
Expired server

### ISSUE THREAD

**Issue by BlockCityNetwork** [yesdog/Waterdog#149]
**Version of Waterdog**
Waterdog-Bootstrap:1.15-SNAPSHOT:96a6c53:24 by md_5

**Expected Behavior**
Bedrock1.16.2 players can enter the server normally.

**Actual Behavior**
When they enter the server, it will say "expired server."

**Crashdump, Backtrace or Other Files**
none

**Describe the bug**
I downloaded WaterDog from here:https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/
,Nukkit is also the latest version (b731)
As he said, this is in support of version 1.16.2:https://github.com/yesdog/Waterdog/issues/147#issuecomment-671074638
I am sure there is nothing wrong with my address. I can read the MOTD information.

**To Reproduce**
1.Use this version of the latest WaterDog:https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/
2.Connect to a Nukkit server that also supports version 1.16.2.
3.You can't enter the server.

**Screenshots**
none

**Server software used:**
Nukkit git-0e7bcbf "" API version 1.0.11 Minecraft: BE V1.16.20 (Protocol version 408)

**Additional context**
If I make any silly mistakes please point out.I'm not very good at Waterdog...

**Comment by Alemiz112** [comment]
Please verify your waterdog config. If server does not log any incomming connection, than something other is usually wrong.

**Comment by BlockCityNetwork** [comment]
> Please verify your waterdog config. If server does not log any incomming connection, than something other is usually wrong.

I am sure my config is correct and I have had no problems with the same config for nearly a month.
But one thing I noticed though is that waterdog's downstream servers need to open the outer network port?I mean, only 19132 port is open to the public.(My English is not very good. I hope you can understand me)

**Comment by Gianluxx** [comment]
Only udp port of waterdog needs internet. Update waterdog to latest and update pmmp/nukkit

**Comment by BlockCityNetwork** [comment]
> Only udp port of waterdog needs internet. Update waterdog to latest and update pmmp/nukkit

I have updated WaterDog to the latest edition(https://ci.codemc.io/job/yesdog/job/Waterdog/315/),and Nukkit is also the latest version.What has changed is that connecting to a server now doesn't show "expired server" but "disconnected from server."(Let me add something about config:The query_port is 19132,listener's port is 19132, lobby's host is 127.0.0.1:19133. Raknet is true)

**Comment by Gianluxx** [comment]
https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/

Btw look at your pmmp/nukkit console for errors

**Comment by BlockCityNetwork** [comment]
> https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/
> 
> 顺便看看您的pmmp / nukkit控制台是否有错误

There were no errors,and server does not log any incomming connection.
Just now I tried to bind the Wide Area Network IP, and unexpectedly I succeeded. Players can enter the waterdog bound server using the Wide Area Network IP.This suggests that Waterdog may not have a problem with itself, but something is preventing it from connecting to the server over the Intranet IP.

**Comment by BlockCityNetwork** [comment]
I take it back. I made a little mistake.But the main problems remain unresolved.

**Comment by Gianluxx** [comment]
If you are hosting all servers in a vps i can help on discord voicechat. join in the official discord in Readme

**Comment by BlockCityNetwork** [comment]
I think I've solved the problem, at least for now.I left my configuration here, hoping to help others in the [future.]
[config.zip](https://github.com/yesdog/Waterdog/files/5101480/config.zip)
