### ISSUE TITLE
Multi protocol for Waterdog

### ISSUE THREAD

**Issue by InVenoxx** [yesdog/Waterdog#152]
As I do so that Waterdog can be multi-protocol so that players from 1.16.0 to the current one enter my Pocketmine server (which is multi version)

**Comment by Alemiz112** [comment]
Waterdog supports multi protocol starting with MCBE 1.8. If your server software is supports multi protocol, it shouldn't be problem.

**Comment by InVenoxx** [comment]
> Waterdog supports multi protocol starting with MCBE 1.8. If your server software is supports multi protocol, it shouldn't be problem.

The thing is, I'm from 1.16.10, I try to get in and I stay in "Loading Resources". But if I go straight into the server from your IP if you let me.

**Comment by Alemiz112** [comment]
Waterdog currently supports only released versions of the game. Betas aren't supported.
