### ISSUE TITLE
Can`t connect to 1.16.40

### ISSUE THREAD

**Issue by JustYarka** [yesdog/Waterdog#157]
I can't log in to the server, it says "connection is broken". There is absolutely nothing in the Waterdog console. 
Mcbe version: 1.16.40
The latest version of Waterdog

**Comment by Alemiz112** [comment]
If you do not see anything in console, then you are probably connecting to wrong address or port.

**Comment by AlexPads** [comment]
This is happening to me as well as other people that I have talked to.

**Comment by laigelplayz** [comment]
This Happens to me. Before its working on 1.16.40 and then 2 days ago. it broke. we can't connect to the server anymore. i tried to Reinstall my server. its still broken.

**Comment by TheSviT** [comment]
Version: 1.16.20
Also does not work:(

**Comment by JustYarka** [comment]
this version works for me: https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/
