### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by CupidonSauce173** [yesdog/Waterdog#159]
I just updated to Build #316 and since then, I just can't join (no players can too) and it says nothing in the console. If you stop WaterDog, you will be in a loading screen until it says that it can't connect to the world but if WaterDog is running, it directly promp you the "Disconnected from Server" and you also get the motd / player count in the server list.

**Comment by CupidonSauce173** [comment]
https://streamable.com/dtj9u0

**Comment by fuyutsuki** [comment]
have the same problem!

**Comment by cujowilliams123** [comment]
I'm also having the same issue.

**Comment by Alemiz112** [comment]
Please if you are able to find duplicates, read the solutions too. If you are in our Discord server, you could see in #news channel post about latest working builds.

You can download working build [here](https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/).

**Comment by fuyutsuki** [comment]
Idk why, but it seems that I was using the latest master build due to my mistake (it wasn't replaced by the one from alemiz-zlib) and it worked anyway, thank you

**Comment by ItzLightyHD** [comment]
So, Waterdog from yesdog isn't updated yet? Ok, thanks.

**Comment by Alemiz112** [comment]
No. It is updated. If you would compile `master-zlib` yourself it would work. For feature discussion related to builds please ask on our Discord server.
