### ISSUE TITLE
Improvements to Resource packs [enhancement]

### ISSUE THREAD

**Issue by cheeseland-dev** [yesdog/Waterdog#160]
**A nice and very helpful feature would be the following improvements to the way waterdog handles Resource Packs.**

Firstly, a very simple feature would be to allow resource packs to not be forced. The expected behavior of this (and how it works with servers) is that the user is prompted to install the pack on join. If they decline it exits them to the main menu. The difference is, users can also have their own resource packs enabled at the same time.

Secondly, a slightly harder, however, also useful feature, would be the ability to switch resource packs between servers. Before you say this isn't possible, I'm aware that you can't add or remove resource packs without loading screens. However, from what I have found there is a data packet for enabling / disabling them, therefor if all the packs were enabled on join, switching servers would simply enable some and disable others. This would also need to come with a configuration to say what servers get what packs etc.

If there are any limitations to my suggestion feel free to lmk, but such features would mean a lot to me as a server owner.

**Comment by TobiasGrether** [comment]
Done on https://github.com/WaterdogPE/Waterdog
