### ISSUE TITLE
Screen being spammed with errors

### ISSUE THREAD

**Issue by CupidonSauce173** [yesdog/Waterdog#170]
When starting the server, with or without plugin, my console does this 
![Screenshot_20201217-110633~2](https://user-images.githubusercontent.com/26697174/102512497-1a735d80-4058-11eb-888c-7a289b722b29.png)

**Comment by TobiasG-DE** [comment]
That looks like some source is sending invalid packets to your server. That might be caused by very old Minecraft server lists or else.

**Comment by CupidonSauce173** [comment]
Look the support channel in the discord server, it's from a different IP, always and when the server opens, it spams hundred of messages like this per second.

**Comment by CupidonSauce173** [comment]
Turns out they were DDoS attacks by overloading the queries with invalid packets. I turned off the query feature and it fixed the problem. The same can happen with PMMP.
