### ISSUE TITLE
Resourcepack download error

### ISSUE THREAD

**Issue by twk1024** [yesdog/Waterdog#172]
**Version of Waterdog**
Waterdog-Bootstrap:1.15-SNAPSHOT:607faf3:15 by md_5

**Expected Behavior**
When I clicked download resource pack, it should be downloaded and automatically join the server.

**Actual Behavior**
When I clicked the download resource pack button, it says 'Encountered a problem while downloading or applying resource pack'

**Crashdump, Backtrace or Other Files**
There was no error logs.

**Describe the bug**
I put my .mcpack resourcepack on the packs folder of proxy and started the server. In the console, it said 'Loaded resource pack 000.mcpack'.
But, when I tried to join my server and downloaded the resource pack, it doesn't work. 
(That resource pack was okay in other normal pmmp servers)

**Screenshots**
<img width="960" alt="error" src="https://user-images.githubusercontent.com/42838268/102951460-42f3cf80-4510-11eb-9a9b-8a2218ca6f31.png">

**Server software used:**
PocketMine-MP

**Comment by Alemiz112** [comment]
Resource packs should be working by now.
