### ISSUE TITLE
 Managing resource packs on proxy connected servers

### ISSUE THREAD

**Issue by ByNamles** [yesdog/Waterdog#173]
When I install a different texture pack on the connected servers, it becomes active on each server, but I want it to be active on a server, how can I do?

**Comment by Alemiz112** [comment]
Hello, deactivating resource packs after player joins game isn't possible from game side.

**Comment by ByNamles** [comment]
But I want to use packi named A on a skyblock server. I don't want it in faction. Isn't there a solution? When I install packi on prox, the same pack is installed on all servers.

**Comment by Alemiz112** [comment]
> Hello, deactivating resource packs after player joins game isn't possible from game side.
Therefore it isn't possible.

**Comment by ByNamles** [comment]
ok thank you
