### ISSUE TITLE
Clear offhand item on transfer

### ISSUE THREAD

**Issue by MasApip** [yesdog/Waterdog#175]
**Version of Waterdog**
Waterdog-Bootstrap:1.15-SNAPSHOT:ea20d8f:18 by md_5

**Expected Behavior**
On transfer to another server the player offhand item must be cleared

**Actual Behavior**
On transfer to another server the player offhand item is not disappear

**Crashdump, Backtrace or Other Files**
No error log

**Describe the bug**
Player offhand item is not disappear on transfer to another server 

**Server software used:**
PocketMine-MP

**Comment by Alemiz112** [comment]
Waterdog is not supposed to clear player's inventory. Downstream software must clear inventory.

**Comment by MasApip** [comment]
okay thank you
