### ISSUE TITLE
Client resource pack doesn't active when add resource pack to server.

### ISSUE THREAD

**Issue by AkmalFairuz** [yesdog/Waterdog#176]
I use shader resource pack, my resource pack active when without resource pack on server. When i add .mcpack file to packs/ server resource pack work, but my shader resource pack (from client) not active.

**Version of Waterdog**
https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/17/

**Expected Behavior**

**Actual Behavior**

**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

1. Add resource pack to server.
2. Use any your resource pack.
3. Join to server.

**Screenshots**

**Server software used:**

**Additional context**

**Comment by Alemiz112** [comment]
Hello, this is normal behavior as packs are enforced by proxy. You might change that manually by disabling force option [here](https://github.com/WaterdogPE/Waterdog/blob/master-zlib/BungeeCord-Patches/0059-Waterdog-PE-additions.patch#L3316).
Next time please open issue on our forked repository, [here](https://github.com/WaterdogPE/Waterdog).
