### ISSUE TITLE
Ver 1.16.201 Cant Connecting

### ISSUE THREAD

**Issue by thinh2118** [yesdog/Waterdog#177]
Do you give me link dowload?

**Comment by Alemiz112** [comment]
Hi, please use build from our new [Jenkins server](https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterdog.jar).

**Comment by thinh2118** [comment]
why when i join server and i go to void?

**Comment by thinh2118** [comment]
not in spawnpoint
