### ISSUE TITLE
Packs does not work.

### ISSUE THREAD

**Issue by RifatFaizZ94** [yesdog/Waterdog#180]
**Version of Waterdog**

**Expected Behavior**

**Actual Behavior**

**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Server software used:**

**Additional context**

**Comment by BlckqFlorian** [comment]
try to use this version ^^

https://jenkins.waterdog.dev/job/Waterdog/job/Waterdog/job/master-zlib/18/artifact/Waterfall-Proxy/bootstrap/target/Waterdog.jar

**Comment by RifatFaizZ94** [comment]
Failed to load pack Title.mcpack: zip END header not found

**Comment by TobiasGrether** [comment]
Should work if your zip file isn't corrupted. Please reopen an issue on the new repo if it's not fixed till then.
