### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by strich3** [yesdog/Waterdog#182]
When i join my server i get kicked nothing shows up in the console! I use the newest version! But on the new version i get kicked :( and on the old i can join!

**Comment by strich3** [comment]
I use powernukkit! Version 1.16.200

**Comment by LegacyGamerHD** [comment]
this version is not maintaned

**Comment by strich3** [comment]
But on Pocketmine it also don‘t work bzw Altay

**Comment by LegacyGamerHD** [comment]
> But on Pocketmine it also don‘t work bzw Altay

its because of the version support

**Comment by TobiasGrether** [comment]
Please refer to https://github.com/WaterdogPE/Waterdog for a newer version
