### ISSUE TITLE
NO WORK IN 1.16.200.02 VERSION ?

### ISSUE THREAD

**Issue by ImHammer** [yesdog/Waterdog#183]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.15-SNAPSHOT:92771ca:317

**Expected Behavior**
Expected to be redirected to the lobby

**Actual Behavior**
Minecraft Kick: Disconnected from server

**Crashdump, Backtrace or Other Files**
NO

**Describe the bug**
when trying to enter the waterdog listener he should be redirected to the lobby, however I am disconnected for the reason "Disconnected from the server"

**To Reproduce**
try to create a waterdog on localhost in version 1.16.200.02 of mcbe

**Screenshots**
-waterdog listener added in minecraft
![Captura de tela de 2021-03-06 20-10-08](https://user-images.githubusercontent.com/59282552/110224229-85df0580-7eb8-11eb-9aa8-edc97486cc4b.png)

-Minecraft diconnected
![Captura de tela de 2021-03-06 20-09-47](https://user-images.githubusercontent.com/59282552/110224246-a0b17a00-7eb8-11eb-8a27-57d95729bb24.png)

-nothing happened in the waterdog
![Captura de tela de 2021-03-06 20-09-57](https://user-images.githubusercontent.com/59282552/110224281-d9515380-7eb8-11eb-878d-362e687a2b22.png)

-waterfall.yml
![Captura de tela de 2021-03-06 20-13-01](https://user-images.githubusercontent.com/59282552/110224301-11f12d00-7eb9-11eb-867d-76a3505b08aa.png)

-pocketmine server.properties
![Captura de tela de 2021-03-06 20-12-56](https://user-images.githubusercontent.com/59282552/110224310-23d2d000-7eb9-11eb-846c-144d650cfbee.png)

-waterdog config
![Captura de tela de 2021-03-06 20-12-36](https://user-images.githubusercontent.com/59282552/110224313-29301a80-7eb9-11eb-8725-def3d843386d.png)
![Captura de tela de 2021-03-06 20-12-50](https://user-images.githubusercontent.com/59282552/110224320-2df4ce80-7eb9-11eb-88dc-1f678d63967b.png)

**Server software used:**
PocketMine

**Additional context**

**Comment by TobiasG-DE** [comment]
make sure you use https://github.com/WaterdogPE/Waterdog

**Comment by IceCruelStuff** [comment]
> make sure you use https://github.com/WaterdogPE/Waterdog

You should link the new repository in the README so everyone will know

**Comment by TobiasG-DE** [comment]
Probably, yea. Gonna close this issue tho.

**Comment by TobiasGrether** [comment]
Done in f67eb9a018af96911e020aa2a0e1703df8ac3da6
