### ISSUE TITLE
Console not opening and pocketmine giving error

### ISSUE THREAD

**Issue by OnyxOykko** [yesdog/Waterdog#184]
**Version of Waterdog**

I have no idea my console don't even open

**Expected Behavior**

I expected to run normally

**Actual Behavior**

When I try to run the console it just closes and when I join Pocketmine it gives error I had to terminate the OpenJDK to even run the servers I use to play with my friends and normally testing stuff I followed this guy's tutorial https://www.youtube.com/watch?v=tBm9LPIPBEA

**Crashdump, Backtrace or Other Files**

https://pastebin.com/raw/sJZZE8RP

**Describe the bug**
The console just crashes and when I run server (PocketMine) It just gives me the error

**To Reproduce**

I don't know
**Screenshots**

**Server software used:**

PocketMine

**Additional context**

**Comment by TobiasGrether** [comment]
Please move to https://github.com/WaterdogPE/Waterdog, try those builds and report if errors still do occur.
