### ISSUE TITLE
BDServer Inaccessible

### ISSUE THREAD

**Issue by xjh2009** [yesdog/Waterdog#187]
[hub@app]server sc XJH9453 
21:03:20 [INFO ] Player XJH9453 was sent to sc server!
21:03:20 [INFO ] [/127.0.0.1:41250|XJH9453] -> Downstream [sc] has connected
21:03:20 [INFO ] [/127.0.0.1:44421|XJH9453] <-> Upstream has disconnected due to failed XBOX authentication!
21:03:20 [INFO ] [/127.0.0.1:41250|XJH9453] -> Downstream [sc] has disconnected

**Comment by TobiasGrether** [comment]
Waterdog is no longer maintained and we are no longer providing support for it. Please check out the README
