### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by AlexPads** [yesdog/Waterdog#19]
Does this speed up transfers between servers on the same network?

and if so does it work on PMMP and also speed up transfers?

also, what is transfer_group in the server adding section in the config and what can it be set to?

ALSO (sry alot of questions) what is ProxyProtocol?

**Comment by TobiasG-DE** [comment]
The Transfer Group specifies where Fast-Transfer is working. When you transfer from one server to another and the servers are in the same Transfer Group, it will speed up the transfer. If they are not in the same TransferGroup, it will do the normal mcpe transfer. And yes, it works with PocketMine-MP

**Comment by AlexPads** [comment]
What can transfergroup be set to? 

And what is proxyprotocol?

**Comment by colinrgodsey** [comment]
transfer group can be set to anything. unless you're using different resource packs, you should be able to leave them all as 'default'

**Comment by AlexPads** [comment]
Thankyou for the info 👌
