### ISSUE TITLE
Game Version, on server Hosts for pmmp report incorrectly

### ISSUE THREAD

**Issue by AlexPads** [yesdog/Waterdog#22]
Also game version on mcpeservers website is reported as 1.9,0 not 1.11.0
Link for proof of bug: https://minecraftpocket-servers.com/server/78760/

**Comment by ErkamKahriman** [comment]
Try to implement Ping Command in WaterDog

**Comment by colinrgodsey** [comment]
You can create a bungee plugin to customize the response version from the ping. right now it just responds with the lowest version it supports because it supports multiversion. hmm, guess ill change the default to show the current release version

**Comment by AlexPads** [comment]
You could add it where you could set what it reports in a config like 
```MC_version: "1.9.0 - 1.11.0"```

**Comment by Alemiz112** [comment]
I think it can stay as it is. 
Showing lowest supported version isnt bad idea. And in server lists it souldnt be problem too. When you have multi-version pmmp it works fine. So with proxy it is on 85% same.

**Comment by AlexPads** [comment]
yes, but on https://minecraftpocket-servers.com when your server reports as an old version it affects your rank and takes down your online time...

**Comment by AlexPads** [comment]
We have made our own plugin to do this so this really shouldn't be an issue anymore. 😄

**Comment by Xernium** [comment]
@AlexPads do you mind sharing it? That’d be greatly appreciated

**Comment by AlexPads** [comment]
Yes I could share I'll make some changes to it soon because as it is rn
it's very much custom to my setup I'll make it a single thing soon 😁
