### ISSUE TITLE
Kick/Ban Messages Not Showing!

### ISSUE THREAD

**Issue by AlexPads** [yesdog/Waterdog#24]
I have Waterdog running a pmmp network.

I have set the Player as banned using my custom ban plugin and when the player gets kicked it says 
```Disconnected from server```

When the player tries to join back it says the same thing and in the waterdog console, it is saying the correct kick and banned messages when the player is trying to connect.

**Comment by lukeeey** [comment]
Probably a client issue

**Comment by AlexPads** [comment]
@lukeeey Its the player getting kicked before the server can send the message... how is that a client issue the ban messages worked just fine without the proxy

**Comment by lukeeey** [comment]
Well you never know the disconnection screen has been fucked for quite some time now

**Comment by colinrgodsey** [comment]
Might be a few things i can try. Guessing that maybe the kick packet doesnt always get sent before the disconnect packet.

**Comment by AlexPads** [comment]
@yesdog
This magically started working again in #218 👍

**Comment by colinrgodsey** [comment]
fixed with newer raknet changes
