### ISSUE TITLE
Resource Packs Feature

### ISSUE THREAD

**Issue by bulutsun** [yesdog/Waterdog#28]
Texture packs not working on waterdog proxy. Please add this feature soon.

**Comment by colinrgodsey** [comment]
- [ ] Should forward first resource pack on initial upstream connection.
- [ ] Should disconnect user with error if connecting to server with different resource pack.
- [ ] Will probably require getting hash of resource pack blob.

**Comment by colinrgodsey** [comment]
implemented in https://github.com/yesdog/Waterdog/commit/c6768e214f9ceada26a8a8f6849bd72ad7648bf4
