### ISSUE TITLE
Skin changes do not show

### ISSUE THREAD

**Issue by DaPigGuy** [yesdog/Waterdog#29]
When your skin is changed by the server, everyone but you can see the changes. Does not occur when connecting directly to the server.

**Comment by ErkamKahriman** [comment]
updatePlayerList

**Comment by NycuRO** [comment]
It's pmmp error.

**Comment by DaPigGuy** [comment]
Changing your skin on your own in the menu also sometimes causes crashes. Only happens when connected through Waterdog

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/090d6636d25d527d59e62181a4d22de1e5bb512d
