### ISSUE TITLE
Hotbar text can't send after initial packet

### ISSUE THREAD

**Issue by Xernium** [yesdog/Waterdog#36]
Any bar displayed like the 'You cant sleep here' bar won't display again after the first packet even if the content is different

**Comment by colinrgodsey** [comment]
Hmmm weird, I can't reproduce this. We use the action bar for some of our plugins, they still work after transfer. That packet also doesnt have anything that would need a rewrite really.... is this for the Title (full screen text) or the action bar?

**Comment by Xernium** [comment]
@colinrgodsey Its a chat packet, and its the action bar. The title bar doesn't work for me either no matter what plugin I try and I dont even need to transfer to have this issue

**Comment by Xernium** [comment]
@colinrgodsey I am a complete utter idiot. Well at least I know now that Waterdog doesn't relay the XUID through(?) to the end server
