### ISSUE TITLE
Falling from sky after switching server

### ISSUE THREAD

**Issue by mpztilera** [yesdog/Waterdog#40]
When I switch the Server with PE, I fall from the sky and am not able to interact with something in the world

**Comment by colinrgodsey** [comment]
That's just how it is for now. Will leave this open as a placeholder incase I feel like trying another approach later.

**Comment by mpztilera** [comment]
Does that mean, that it is currently not playable with Bedrock Edition?

**Comment by TobiasG-DE** [comment]
It is, I currently use it in production without any errors when transferring from pm to pm

**Comment by Legit4K** [comment]
Seems to kill players after transfer due to fall damage, would a temp solution like disabling fall damage for 5 seconds upon spawning work?

**Comment by TobiasG-DE** [comment]
I think you have a misconfiguration there somewhere, beceause for me, it works without any fall damage hackaround :/
Can others confirm the appearing of those fall damage death bugs?

**Comment by Xernium** [comment]
@Legit4K @TobiasG-DE Thats a setting for the servers purely because the connection may drop some packets at the start. In my testing it works fine with NukkitX PSPE and PMMP so I can't say for sure. Maybe increase connection threshold

**Comment by mpztilera** [comment]
I have the problem on both, NukkitX and PSPE, but on PSPE I only cant interact with the world while on NukkitX I cant see anything in the world.

**Comment by mpztilera** [comment]
I just testet it with a fresh installation of Waterdog, but still the same issue

**Comment by colinrgodsey** [comment]
if the world never loads in nukkit, something else is wrong there

**Comment by mpztilera** [comment]
Nukkit is loading correctly, when I configure Waterdog to directly connect me to nukkit everything works fine.

**Comment by mpztilera** [comment]
When i try to connect with Bedrock to the newest version of Waterdog I get this error: https://pastebin.com/HhVxfma2

**Comment by colinrgodsey** [comment]
using nukkit as the backend server?

**Comment by mpztilera** [comment]
No, PSPE

**Comment by InsaneLegacy** [comment]
works fine for me

am running in to other issue

**Comment by mpztilera** [comment]
Can it be, that my issues have something to do with the transfer_group? How should I set them when I use Bedrock Servers?

**Comment by TobiasG-DE** [comment]
TransferGroups can be used if you want the Fast Transfer only between specified servers. If you teleport from server 1 to server 2 and they are in different transfer groups, the proxy will do the slow MCPE default Transfer

**Comment by mpztilera** [comment]
Can someone who has it working please send me his config file?

**Comment by colinrgodsey** [comment]
This is definitely a weird problem. Some servers seem to have a different spawn pattern on load than others. Need to think of a way to unify em

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/d45b26e40b00407db037d66ec2304be10e28e5ed

**Comment by mpztilera** [comment]
Sadly still the same problem :(

**Comment by Xernium** [comment]
@mpztilera please try to use the fallback transfer method: Put all servers in different transfer groups and disable the force default server on join. (If you get stuck in a loop that always sends you to the same server disable your waterdog plugins one by one till it starts working). If that doesn’t help please come back here
