### ISSUE TITLE
How to fix ? :v

### ISSUE THREAD

**Issue by hachkingtohach1** [yesdog/Waterdog#45]
![Screenshot (1615)](https://user-images.githubusercontent.com/29000265/61992436-b5951d00-b088-11e9-98c9-69e7f7bea194.png)

I have very tried to change the firewall check changes

**Comment by Xernium** [comment]
@hachkingtohach1 Please provide an anonymized copy of your waterdog and your end servers configs as well as the logs that are generated when trying to connect

**Comment by hachkingtohach1** [comment]
@Xernium  @@ 
[Proxy.zip](https://github.com/yesdog/Waterdog/files/3438085/Proxy.zip)

**Comment by Xernium** [comment]
`listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    foxcraft.ddns.net: lobby
  ping_passthrough: false
  raknet: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
- query_port: 19132
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
  ping_passthrough: false
  raknet: true
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:19132
  max_players: 20
  tab_size: 100
  force_default_server: false
bedrock_encryption: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
log_commands: true
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
use_xuid_for_uuid: true
connection_throttle: 4000
replace_username_spaces: true
stats: c1b86ccb-d4dd-4cd8-b4d9-5584276b6202
network_compression_threshold: 256
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    raknet: true
    motd: '&1skywars'
    transfer_group: default
    address: 0.0.0.0:19136
    restricted: false
`

**Comment by Xernium** [comment]
https://pastebin.com/qnTBFxfP @hachkingtohach1 the server has to have ranknet: true if its a bedrock server. Also access restriction is broken so restricted: true will break a few things. Lastly I removed the broken hosts. Give that a try.

**Comment by colinrgodsey** [comment]
For network and configuration help, join the discord here https://discord.gg/VA8VgCz.
