### ISSUE TITLE
NOT Issue, Question | Hub Command

### ISSUE THREAD

**Issue by PocketMiner82** [yesdog/Waterdog#46]
I wan't to create a /hub command in PMMP(!). And I don't know how should I tell WaterDOg, that it should transfer a player to the server "Lobby". Does anybody know, how this works? Thanks 😀

**Comment by colinrgodsey** [comment]
You can see an example of how to do that with PMMP here: https://github.com/yesdog/WaterdogTools/tree/master/transfercommand-pocketmine

If you have any other questions, the best place to ask them is in the discord here: https://discord.gg/VA8VgCz

**Comment by Xernium** [comment]
Damnit you beat me to it @colinrgodsey ;)
