### ISSUE TITLE
"Query - Incorrect magic!:"

### ISSUE THREAD

**Issue by Artuto** [yesdog/Waterdog#47]
I'm getting "Query - Incorrect magic!:" all spammed in the console.

According to this Spigot post: https://www.spigotmc.org/threads/query-incorrect-magic-and-high-cpu-usage.159386/#post-2709057

It may be due Windows 10 Edition clients pinging the server in the query port (mine is 25565) and causing these types of issues.

This seems like a valid reason because Waterdog supports PE and my server supports it.

**Comment by colinrgodsey** [comment]
So this might actually be a better fix for waterfall. The query listener on raknet listeners, we disable that message. So that must someone be coming from the normal java listener, and we dont really modify the behavior there

**Comment by Artuto** [comment]
I dont think Bungee or Waterfall would accept this issue because first, they are not meant to be used with bedrock edition clients, unlike Waterdog, and second, https://github.com/SpigotMC/BungeeCord/issues/1055#issuecomment-46145177

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/d45b26e40b00407db037d66ec2304be10e28e5ed
