### ISSUE TITLE
Metadata Wipe

### ISSUE THREAD

**Issue by TobiasG-DE** [yesdog/Waterdog#48]
Metadata should be wiped on server switch or at least the status effects the player has. At the current state, if a player gets effect on one server and switches to another server, he keeps those effects, which it seems can't be removed by plugins on downstream server after that ( ? ).

**Comment by Xernium** [comment]
@TobiasG-DE Yeah youre right. I thought I could avoid the issue for a bit longer but it seems I need to do something about it. For now you could use the other transfer method if it bugs you too much

**Comment by Xernium** [comment]
Turns out using the fast transfer method breaks the Players entitiy meta before the transfer as can be seen when you transfer to the Server you're already on. Only fixable by sending the clearing packets before

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/d45b26e40b00407db037d66ec2304be10e28e5ed
