### ISSUE TITLE
Cannot join to the waterdog proxy through another proxy server

### ISSUE THREAD

**Issue by GamakCZ** [yesdog/Waterdog#54]
**Version of Waterdog**

All latest

**Expected Behavior**

Connect to the server through 2 proxies

**Actual Behavior**

Second proxy throws error

**Crashdump, Backtrace or Other Files**

https://hastebin.com/acejevoxoz.bash

**Describe the bug**

⬆️ 

**To Reproduce**

Connect to the first proxy server that is set to the second proxy server

**Screenshots**

**Server software used:**

1. Server - Waterdog (localhost)
2. Server - Waterdog (VPS)
3. Server - PocketMine (VPS) (Nothing about connect in the console)

**Additional context**

Ip forward turned on

**Comment by colinrgodsey** [comment]
Need to set the middle proxy to offline mode. Using 2 proxies like that in a chain is definitely not an intended usecase, but should work if you disable online mode (Set to offline) the second proxy
