### ISSUE TITLE
Skin change kicks player

### ISSUE THREAD

**Issue by GamakCZ** [yesdog/Waterdog#55]
**Version of Waterdog**

Latest

**Expected Behavior**

Skin should be changed

**Actual Behavior**

Player got kicked from the server

**Crashdump, Backtrace or Other Files**

https://hastebin.com/quzobufuwi.bash

**Describe the bug**

title

**To Reproduce**

Change skin

**Screenshots**

**Server software used:**

PMMP latest release

**Additional context**

**Comment by AlexPads** [comment]
can approve this happens on the latest release.
