### ISSUE TITLE
I  get an error with a CustomBlockData on item

### ISSUE THREAD

**Issue by LucGamesYT** [yesdog/Waterdog#56]
**Version of Waterdog**
Waterfall version git:Waterdog-Bootstrap:1.14-SNAPSHOT:5a2d840:272

**Expected Behavior**

No error and no kick

**Actual Behavior**

I get an error and i will kicked

**Crashdump, Backtrace or Other Files**
https://hasteb.in/orozixez.lua

**Describe the bug**
If I click the item in the inventory or scroll on it then I am kicked and get an error

**To Reproduce**
Make in Nukkit a customBlockData on item and scroll on the item or klick on them

**Screenshots**

**Server software used:**

Nukkit Latest

**Additional context**

**Comment by Alemiz112** [comment]
Hello, is this still the issue? Can I close it?

**Comment by TobiasGrether** [comment]
Closed due to inactivity
