### ISSUE TITLE
I get an error when you change the skin in the game.

### ISSUE THREAD

**Issue by LucGamesYT** [yesdog/Waterdog#58]
**Version of Waterdog**
 Waterfall version git:Waterdog-Bootstrap:1.14-SNAPSHOT:23f03cd:275

**Expected Behavior**
No error

**Actual Behavior**
I get an error

**Crashdump, Backtrace or Other Files**
<<redacted>>

**Describe the bug**
If you want to change the skin in the game, an error occurs in the console

**To Reproduce**
Change the Skin Inagme

**Screenshots**

**Server software used:**
Nukkit

**Additional context**

**Comment by Xernium** [comment]
Edited: removed hastebin link

**Comment by Erkam246** [comment]
disable bedrock_encryption
