### ISSUE TITLE
Random kick

### ISSUE THREAD

**Issue by Erkam246** [yesdog/Waterdog#60]
**Version of Waterdog**

This server is running Waterdog version git:Waterdog-Bootstrap:1.14-SNAPSHOT:85410b6:278 by md_5
**Expected Behavior**

Play without getting kicked every 10 minutes within to 2 hours

**Actual Behavior**

Players getting kicked after an interval
**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

Just connect to any server
**Screenshots**

![image](https://user-images.githubusercontent.com/16340573/64593107-bde1b700-d3ad-11e9-9585-3df8cf2d9fed.png)

**Server software used:**

Pocketmine
**Additional context**

**Comment by colinrgodsey** [comment]
does anything show up in the server logs?

**Comment by Erkam246** [comment]
Nope nothing

**Comment by thehexmor** [comment]
this is my problem too . fix it

**Comment by thehexmor** [comment]
there is nothink in waterdog or pocketmine logs

**Comment by TobiasG-DE** [comment]
This is not the case of my production network, so I assume it is caused by a misconfiguration or by a missing plugin

**Comment by Xernium** [comment]
@TobiasG-DE I suppose its caused by an unclean shutdown or an interrupted connection. Ive seen this multiple times but all aren't reproducible in my production environments

**Comment by TobiasG-DE** [comment]
I think this could be caused by pmmp packet amount restrictions. You can only send a specific amount of packets through one ip per second, if this hits a treshold, ip gets blocked for 5 seconds. Means that all players are disconnected bc they all inherit the same ip ( IP of Proxy Server )

**Comment by TobiasG-DE** [comment]
Try using this plugin, it should remove packet treshold https://github.com/lukeeey/WaterdogPM

**Comment by Erkam246** [comment]
This was not the problem but it happend only the first week while waterdog was running in production
