### ISSUE TITLE
Issue connecting to PMMP

### ISSUE THREAD

**Issue by lukeeey** [yesdog/Waterdog#63]
I get the following error when connecting to PMMP (4.0 master branch) in offline mode:
```
Session closed due to Invalid session. Reason: Unexpected XUID for non-XBOX-authenticated player
```

I have `use_xuid_for_uuid` set to true. The issue also occurs if its set to false.
`xbox-auth` is set to false in PMMP

This issue does not occur with Nukkit, so i assume they do not have as strict checks.

**Comment by Alemiz112** [comment]
First its development build, pmmp 4.0.0 is diffrent than stable branch. We will look on it soon :P

**Comment by colinrgodsey** [comment]
This still an issue?

**Comment by colinrgodsey** [comment]
@dktapps - Do you know if thise behavior is going to be maintained after the beta? Kind of sucks to not be able to send the XUID over the official channels there.

**Comment by dktapps** [comment]
Yes, I have no plans to change this behaviour. On PM3 the XUID would silently be replaced with an empty string in this case anyway, so it doesn't make a whole lot of difference.

**Comment by Pab450** [comment]
@colinrgodsey It still is but it's possible to bypass it very easily.

**Comment by TobiasGrether** [comment]
Fixed by PM4s changed implementation.
