### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tunikakeks** [yesdog/Waterdog#67]
**Version of Waterdog**

**Expected Behavior**

**Actual Behavior**

**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Server software used:**

**Additional context**

Please Update to mcbe / mcpe 1.13.x and also update the latest .jar file. Thanks!

**Comment by colinrgodsey** [comment]
Update coming soon. Watch the discord for more details

**Comment by colinrgodsey** [comment]
duplicate of #68
