### ISSUE TITLE
block palette bug

### ISSUE THREAD

**Issue by EinBexiii** [yesdog/Waterdog#70]
Version of Waterdog
latest

Expected Behavior
nothing

Actual Behavior
When you click on a block, other blocks spawn.

Describe the bug
When you click on a block, other blocks spawn.

To Reproduce
Right click on a block

Screenshots

Server software used:
Nukkit

**Comment by colinrgodsey** [comment]
can't reproduce using the bedrock-1.13 branch of nukkit. what branch are you using for 1.13?

**Comment by Alemiz112** [comment]
I can confirm that. Probably is caused by different block pallets between servers. There are lot of own forks for 1.13 servers. This forks can have different block pallete than WaterDog.

**Comment by Wertzui123** [comment]
Happens to me at PocketMine 3.11.1 too

**Comment by FlussRaplay** [comment]
The Bug is fixed by KCodeYT

**Comment by GamakCZ** [comment]
It works when player connect to the first server, but after transfer it's bugged

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/403f2f7d76c6569322a9f678b926a51853f56dee
