### ISSUE TITLE
Error while connecting with MCPE 1.13.1

### ISSUE THREAD

**Issue by Wertzui123** [yesdog/Waterdog#75]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.14-SNAPSHOT:ee0f6dc:291 by md_5

**Expected Behavior**
Regular join

**Actual Behavior**
Spamms console with skin data/textures (**ca. 20000 lines**), throws error and kicks player

**Crashdump, Backtrace or Other Files**
https://hasteb.in/purefara.lua

**Describe the bug**
Spamms console with skin data, throws error and kicks player

**To Reproduce**
Join a waterdog server with MCBE 1.13.1 for android

**Screenshots**

**Server software used:**
PocketMine

**Additional context**

**Comment by Wertzui123** [comment]
At the beginning of the error, there is:

https://hasteb.in/mapibegi.rb

**Comment by NxtUser-HD** [comment]
For me works all fine. (1.13 + 1.14-BETA). I don't become any error and i don't get kicked. lol

**Comment by CupidonSauce173** [comment]
> For me works all fine. (1.13 + 1.14-BETA). I don't become any error and i don't get kicked. lol

I do get kicked.

**Comment by Alemiz112** [comment]
What skin are you using? Steve/Alex or custom or 1.13 custom skin??

**Comment by Wertzui123** [comment]
Tried steve and a custom skin with a cape from the Character creator.

**Comment by Wertzui123** [comment]
Does now work for any reason. lol
