### ISSUE TITLE
Resource packs don't work

### ISSUE THREAD

**Issue by Wertzui123** [yesdog/Waterdog#76]

**Comment by Wertzui123** [comment]
Could you add support for resource packs please?

**Comment by provsnoobgaming** [comment]
there already is?

**Comment by Wertzui123** [comment]
When I use a server with a rp but the client doesn't changes textures

**Comment by colinrgodsey** [comment]
RPs must be configured in Waterdog, they can't be configured on the backend servers. Information on how to use RPs with Waterdog is in the readme: https://github.com/yesdog/Waterdog

**Comment by Wertzui123** [comment]
But I only want it on one server. When I change the transfer group, I'm just transfered to the lobby

**Comment by colinrgodsey** [comment]
You can't change resource packs if you're doing fast-transer. there's no packet to reload the resource packs, they can only be loaded on initial signin, so its impossible to change them when transferring servers like you're talking about. there's some other packet you can use to enable/disable already-loaded RPs, but i don't know what it is.

**Comment by Wertzui123** [comment]
But when I change the transfer group, I'm just transfered to the lobby

**Comment by Xernium** [comment]
@Wertzui123 This will only work if you disable the setting that forces players to log into the default server.

**Comment by Wertzui123** [comment]
Wich?

**Comment by Wertzui123** [comment]
> Wich?

force_default_server: false
