### ISSUE TITLE
Something is crashing the PE client

### ISSUE THREAD

**Issue by Artuto** [yesdog/Waterdog#8]
After you added the IdentityManagement event and I recoded AccountsLink with it my PE crashes out of nowhere on the login phase. 

Bungee console just shows "Timed out", the backend server with PSPE shows nothing, even with debug mode enabled.

The only way i was able to stop the crashing was to remove the plugin or just unlink my accounts.

PE 1.11 - Latest Waterdog

**Comment by colinrgodsey** [comment]
Issue located, something PSPE related

**Comment by TobiasG-DE** [comment]
Has this been fixed yet?

**Comment by colinrgodsey** [comment]
This particular issues, yes.
