### ISSUE TITLE
MOTD is displayed wrong

### ISSUE THREAD

**Issue by GamakCZ** [yesdog/Waterdog#80]
**Version of Waterdog**

git:Waterdog-Bootstrap:1.15-SNAPSHOT:a1a01bc:298

**Expected Behavior**

It should display bold colors

**Actual Behavior**

It displays the colors but without the bold format

**Crashdump, Backtrace or Other Files**

- How it seems
![image](https://user-images.githubusercontent.com/17053298/71418109-1a20cc00-2669-11ea-8b7f-18ca6034cbf5.png)

- Config
![image](https://user-images.githubusercontent.com/17053298/71418075-02494800-2669-11ea-9f77-7f8ae229b8ec.png)

**Additional context**
- Yes, I'm using UTF-8 encoding
- It seems that this wrong format have been displayed on query too
![image](https://user-images.githubusercontent.com/17053298/71418171-69ff9300-2669-11ea-8400-edf571086e35.png)

**Comment by Alemiz112** [comment]
Try using `&` instead `§`.

**Comment by Wertzui123** [comment]
Doesn't work, still not bold

**Comment by colinrgodsey** [comment]
Can anyone confirm that this is even possible with the bedrock MOTD?

**Comment by Alemiz112** [comment]
I can conform it. And it works well with `&l` for me.

Config:
![image](https://user-images.githubusercontent.com/45739737/71419167-5c98d780-266e-11ea-9e69-887fd4a2d4bf.png)

Result:
![image](https://user-images.githubusercontent.com/45739737/71419177-6e7a7a80-266e-11ea-8f23-dc043793a683.png)

**Comment by Wertzui123** [comment]
motd: "&l&2Wertzui&4Games &7> &r&cWartungsarbeiten"

Doesn't work

**Comment by colinrgodsey** [comment]
oh right, you need to put the color code first, then the 'l' for bold.

**Comment by Alemiz112** [comment]
But why 🤔

**Comment by Wertzui123** [comment]
Every time after a new color code is used?

**Comment by Wertzui123** [comment]
No, OK thanks

**Comment by Wertzui123** [comment]
But &r doesn't work

**Comment by colinrgodsey** [comment]
yea, color codes reset styling. thats why you can do &0 to reset all the styling. so all styling has to come after the color code

**Comment by Wertzui123** [comment]
When I use &0 it's black but still bold

**Comment by GamakCZ** [comment]
![image](https://user-images.githubusercontent.com/17053298/71426089-1317af00-26a5-11ea-97c1-ea941e855ff4.png)

causes this

![image](https://user-images.githubusercontent.com/17053298/71426092-1b6fea00-26a5-11ea-83d9-a893c9dbf0e9.png)

._.
