### ISSUE TITLE
Weather, Time, Gamerules stays same after transfer

### ISSUE THREAD

**Issue by Erkam246** [yesdog/Waterdog#82]

**Comment by Alemiz112** [comment]
Can confirm

**Comment by Wertzui123** [comment]
too

**Comment by Alemiz112** [comment]
I can look on it if I will find some time.

**Comment by Alemiz112** [comment]
Gamerules are fixed. For some reason weather (LevelEventPacket) is ignored by player. Needs to find out why.

**Comment by Alemiz112** [comment]
Weather was fixed aswell.
