### ISSUE TITLE
Türkensoftware support @everyone

### ISSUE THREAD

**Issue by nextexr** [yesdog/Waterdog#84]
**Version of Waterdog**

**Expected Behavior**
It works 

**Actual Behavior**
it didnt work

**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Server software used:**
Türkensoftware

**Additional context**

**Comment by Xernium** [comment]
Trolling will get you specifically excluded from the project. Do not waste our time.
