### ISSUE TITLE
If I try to hit a player I get damage

### ISSUE THREAD

**Issue by EinfachWolf-codeZ** [yesdog/Waterdog#85]
**If I try to hit a player I get damage**

As soon as I carry out a transfer and try to hit someone, I get damage and the opponent not this error only occurs sometimes

I know there is the bug on PeazyGames.net there on Bedwars I have had it many times

**Comment by EinBexiii** [comment]
I can confirm that.

**Comment by Virvolta** [comment]
I can confirm that.

**Comment by Erkam246** [comment]
I too

**Comment by DavinGindorf** [comment]
I too

**Comment by noxi69** [comment]
i have this probleme

**Comment by Wertzui123** [comment]
> 
> 
> I can confirm that.

I can confirm it too.

**Comment by NxtUser-HD** [comment]
same

**Comment by Alemiz112** [comment]
Does it happen on PMMP only?

**Comment by Virvolta** [comment]
i used PMMP 3.11.1

**Comment by EinBexiii** [comment]
I don't know why, but I had the bug once but with Nukkit. @Alemiz112

**Comment by EinfachWolf-codeZ** [comment]
> Does it happen on PMMP only?

We use an altay fork

**Comment by EinfachWolf-codeZ** [comment]
> Does it happen on PMMP only?

> I don't know why, but I had the bug once but with Nukkit. @Alemiz112       

> i used PMMP 3.11.1

> We use an altay fork

Apparently it is common to any server software

**Comment by Alemiz112** [comment]
Does anyone do deep test if it does appear without proxy? Can someone test it?

**Comment by EinfachWolf-codeZ** [comment]
> Does anyone do deep test if it does appear without proxy? Can someone test it?

NxtUserHD tested it in 10 out of 10 tests, the bug came 0 times without proxy

**Comment by Alemiz112** [comment]
And with proxy?

**Comment by EinfachWolf-codeZ** [comment]
> And with proxy?

NxtUserHD says: I tested on 4 different sub-servers and it came 3 times out of 4 attempts

**Comment by Alemiz112** [comment]
Okay. So it happens only after transfer?

**Comment by EinfachWolf-codeZ** [comment]
> Okay. So it happens only after transfer?

yes

**Comment by TobiasG-DE** [comment]
Maybe the EntityIds are getting mixed up again in the transfer for some awkward reason

**Comment by Alemiz112** [comment]
@TobiasG-DE I think it could be by entity runtime id too.

**Comment by TobiasG-DE** [comment]
That's what I meant :sweat_smile:

**Comment by TobiasG-DE** [comment]
Should be fixed in newer versions already

**Comment by EinfachWolf-codeZ** [comment]
> Should be fixed in newer versions already 

Jo der bug ist allgemein schon alt

**Comment by Wertzui123** [comment]
Nice, thanks.
