### ISSUE TITLE
Players are disappearing 

### ISSUE THREAD

**Issue by LelouBil** [yesdog/Waterdog#88]
Players are sometime dissapearing using git:Waterdog-Bootstrap:1.15-SNAPSHOT:81eb6a5:300 and the official server software. It could be a duplicate of #51

**Comment by Wertzui123** [comment]
Yea, I think it's the same bug as #51

**Comment by TobiasG-DE** [comment]
That's a weird issue. Are there any patterns with the players disappearing and is there any way to reproduce it, f.e. is it happening when transferring to another Server?

Regards,
TobiasDev

**Comment by TobiasG-DE** [comment]
Btw reading #51, this should be an Issue with BDS only, what is confusing, but might be worth looking into.

**Comment by Alemiz112** [comment]
I believe this is already fixed as we havent heard anything similar since this issue. You can reopen issue if needed.
