### ISSUE TITLE
Issue to connect to Server that are not localhost

### ISSUE THREAD

**Issue by belohnung** [yesdog/Waterdog#93]
**Version of Waterdog**
git:Waterdog-Bootstrap:1.15-SNAPSHOT:9c99812:302 by md_5

**Expected Behavior**
I get connected to the server not located on the same machine

**Actual Behavior**
I get kicked with the Message: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException

**Crashdump, Backtrace or Other Files**
Configuration: https://hastebin.com/ihumuwokoh.yml

**Describe the bug**
I get kicked when i join, but only if the server is not on localhost

**To Reproduce**
Get a second machine with another ip and start a PocketMine Server there and register it in the config

**Server software used:**
Pocketmine

**Comment by Alemiz112** [comment]
Im network setup looks exactly same. How big is ping delay between machine?

**Comment by belohnung** [comment]
35ms

**Comment by TobiasG-DE** [comment]
Are you sure there are no firewalls or port configurations messing with the connection? Have you tried to join the server directly?

**Comment by belohnung** [comment]
yes i did

**Comment by TobiasG-DE** [comment]
And that is working?

**Comment by belohnung** [comment]
no still not

**Comment by belohnung** [comment]
i can join directly but not over the proxy

**Comment by TobiasG-DE** [comment]
Any log output from the PocketMine Server or any plugins on it that could cause interferences?

**Comment by belohnung** [comment]
no none on both, and no connection attempt log in pmmp

**Comment by NxtUser-HD** [comment]
Can confirm that

**Comment by TobiasG-DE** [comment]
Hmm that's odd. This needs to be due to one of the latest commits, as in my older version, it works just fine

**Comment by belohnung** [comment]
maybe mtu related cause i read that being an issue for some users on Pocketmine

https://github.com/pmmp/PocketMine-MP/issues/2353

**Comment by TobiasG-DE** [comment]
Shouldn't be an MTU Problem, works fine on the networks I'm working for, but I'm not using the latest version tho

**Comment by belohnung** [comment]
especially then it could be an mtu problem

**Comment by TobiasG-DE** [comment]
I think there were some Netty changes In one of the latest commits, might be a result of those commits

**Comment by TobiasG-DE** [comment]
* Oops nvm that was some time ago. I'll look into that once I found time

**Comment by belohnung** [comment]
any updates?

**Comment by TobiasG-DE** [comment]
Not really, haven't found time to look into that. Can you maybe provide me your Waterdog Jar per Discord?

**Comment by Alemiz112** [comment]
I use servers with custom addresses (not localhost) only. It works well. Im using latest waterdog. But my pmmp is older. I dont think it is due to netty upstream update. It looks more like pmmp related stuff.

**Comment by belohnung** [comment]
i dont know what fixed it but my selfbuilt jar worked
