### ISSUE TITLE
Problem mit Waterdog-Crashes! -problem with waterdog crashes-

### ISSUE THREAD

**Issue by DueKay** [yesdog/Waterdog#99]
**Version of Waterdog**

[11:23:09 INFO]: This server is running Waterdog version git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303 by md_5

**Expected Behavior**

German:
Erwarten würde ich von Waterdog, dass dauerhaft 0/500, in der Konsolen Übersicht steht! (Da wir den Server mit Waterdog auf 500 User begrenzt haben, was die Zusammenfassung aller möglichen User, auf unseren NukkitX Servern ist) Und der Server nicht einfach crasht, nur weil User einfach die App auf dem Handy schließen, ohne sich vorher bei Minecraft ausgeloggt zu haben, bzw. zu schlechtes Internet haben!
English:
I would expect from Waterdog that permanently 0/500 is in the console overview! (Since we have limited the server with Waterdog to 500 users, which is the summary of all possible users on our NukkitX servers) and the server does not simply crash just because users simply close the app on their mobile phone without first logging out of Minecraft to have, or to have bad internet!

**Actual Behavior**

German:
Tatsächlich ist es allerdings so, dass der Waterdog Server täglich mehrfach Crasht! Auch die Ursache ist uns derweil bekannt, bzw. sehen wir schon in der Konsolen Übersicht wenn der Waterdog Server down ist und niemand mehr joinen kann, da dort dann 0/0 User stehen!
English:
In fact, the Waterdog Server crashes several times a day! The cause is also known to us in the meantime, or we can already see in the console overview if the Waterdog Server is down and no one can join, because there are 0/0 users!

**Crashdump, Backtrace or Other Files**

https://hastebin.com/mogeyigowo.md

**Describe the bug**

German:
Der Fehler besteht daraus, dass der Waterdog Server Täglich mehrfach crasht! Die NukkitX Server hingegen zeigen keinerlei Fehlermeldungen in der Konsole an! Den Auszug, der Waterdog Konsole hab ich hier mit rein kopiert, über die vorgegebene Website, im vorgegebenen Bereich!
Sobald der Server gecrasht ist, kein User mehr joinen kann und in der Übersicht 0/0 steht, ist der Server zwar laut Minehub.de noch Pingbar, allerdings dennoch down bis ich ihn einmal Restarte. Ganz selten kommt es auch vor, dass der Server öfter restartet werden muss. Oder er nach einem Restart oflline ist und ich auf Starten drücken muss…
Wodurch das passiert, dass der Waterdog Server crasht?
Dies liegt scheinbar an den Usern und ich hoffe ihr könnt für den Bug ein Update rausbringen, wodurch das nicht mehr passieren kann.
Crashen tut er dann wenn:
- User einfach die Minecraft App schließen, ohne sich vorher ausgeloggt zu haben!
- User eine zu schlechte Internet Verbindung haben oder das Wlan plötzlich ganz weg ist!
In beiden fällen loggen die User sich dann meistens/eigentlich immer nur auf dem NukkitX Server aus, aus welchem sie sich befanden und nicht bei der Lobby, welcher der HauptServer ist!
User die sich normal ausloggen, loggen sich „immer“ bei dem aktuellen NukkitX Server aus UND bei dem Lobby Server! (Dies konten wir im Log kontrollieren!)
Wenn alles so ist wie es soll:
join lobby
left lobby
join cb
left cb
left lobby
Wenn User sich nicht ordentlich ausloggen:
join lobby
left lobby
join cb
left cb
Und Sry das die Erklärung so lang wird. Aber möchte mich möglichst klar ausdrücken. Hatte zuvor schon versucht das Problem mit 2 euerer Leute anzugehen, aber leider ohne Erfolg. Diese Personen waren FIVE und Tobias. Wobei mir FIVE generell nicht mehr antwortet und Tobias mich schlussendlich auf die Issuses verwiesen hatte…
English:
The error is that the Waterdog Server crashes several times a day! The NukkitX servers, however, do not display any error messages in the console! I copied the excerpt, the Waterdog console here, over the specified website, in the specified area!
As soon as the server has crashed, no more users can join and the overview is 0/0, the server is still pingable according to Minehub.de, but still down until I restart it. It also happens very rarely that the server has to be restarted more often. Or he is online after a restart and I have to press Start ...
How does the Waterdog Server crash?
This is apparently due to the users and I hope you can bring out an update for the bug, which means that this can no longer happen.
He then crashes when:
- Users simply close the Minecraft app without first logging out!
- Users have a bad internet connection or the wifi is suddenly gone!
In both cases, the users usually / actually only ever log out of the NukkitX server from which they were located and not from the lobby, which is the main server!
Users who log out normally, "always" log out of the current NukkitX server AND the lobby server! (We could check this in the log!)
If everything is as it should be:
join lobby
left lobby
join cb
left cb
left lobby
If users do not log out properly:
join lobby
left lobby
join cb
left cb
And Sry that the explanation will be so long. But I want to be as clear as possible. I tried to deal with the problem with 2 of your people before, but unfortunately without success. These people were FIVE and Tobias. Although FIVE generally doesn't answer me anymore and Tobias finally referred me to the issues ...

**To Reproduce**

German:
Ich hoffe ich verstehe das Richtig und ich soll hier nochmal erklären, wie ihr das zum Testen reproduzieren könnt!?!?
Kann nicht so gut Englisch und arbeite mit Google Übersetzer. Schreibe absichtlich das Deutsche mit rein, da ich weiß, dass ihr Teamler habt, die Deutsch und Englisch können! So hoffe ich dass ich das Problem best möglichst verständlich rüber bringen kann!
Zum Testen den Fehler reproduzieren, sollte nicht schwer sein…
- Man braucht mindestens 2 NukkitX Server (unsere werden bei Minehub.de gehostet. Aber an denen liegt es wohl nicht)
- Man braucht einen Waterdog Server
- Man verbinde diese Server mit einander (wie sollte ich ja nicht erklären müssen xD)
- Wenn man alles richtig eingestellt hat, joint man dem Server-System (vorzugsweise über Handy. Bei PC tritt es zwar auch auf, allerdings recht selten. Sind noch nicht lange mit PC dabei, deshalb fiel es erst später auf, dass es dort nicht zwingen passiert. Allerdings wurde die Minecraft Version ja überwiegend für Handy User hergestellt. Die meisten User nutzen es auch über Handy, weshalb es mehr als ärgerlich ist)
- Dann ist es egal ob man auf dem ersten Server bleibt oder auf einem zweiten joint. (Bleibt man auf dem ersten loggt er sich natürlich nur einmal aus wenn man disconnectet und auch nirgends anders. Joint man auf einen zweiten müsste man eigentlich auch im ersten disconnecten, so gesehen sollte man 2 mal offline gehen.)
- Der nächste und letzte schritt ist simpel. Bringt den Server zum crashen, damit ihr den Fehler selbst Reproduzieren könnt. Dies macht ihr entweder, indem ihr die App schließ ohne euch auszuloggen, mit einer sehr schwachen Verbindung online geht, oder indem ihr euch das Wlan klaut wenn ihr online seid!
- wundert euch auch nicht, wenn der Server nicht beim ersten mal down geht. Um euch die aktuelle Konsolen Ausgabe kopieren zu können, hab ich mit 2 Teamlern den Server down gelegt, dabei war ich bestimmt 5 mal on bis es so weit war und die anderen beiden 2-3 mal. 
Teamintern ist der Fehler bekannt, den Usern allerdings zum Glück noch nicht. Der Schuss könnte nämlich nach hinten los gehen, wenn es dazu kommt…
-Wenn ihr sehen möchtet, wie das ganze aussieht, wenn +/- 8-15 User online sind (im stream sieht man leider immer nur die User des aktuellen Servers) schaut gerne mal in die streams bei uns rein. In jedem Crasht der server mindestens 1 mal (außer es ist ein sehr kurzer stream dabei) Es gibt auch streams, oder allgemein situaionen, wo der server mehrfach hintereinander down geht oder auch mal ne Zeit lang gar nicht wieder angehen möchte…
https://www.youtube.com/channel/UCm-ZRmINaO1GIvOQOPaY6zw/videos?view_as=subscriber 
English:
I hope I understand correctly and I should explain again how you can reproduce this for testing!?!?
Can't speak English well and work with Google Translate. Intentionally write in the German as I know that you have team members who can speak German and English! So I hope that I can get the problem across as easily as possible!
Reproducing the error for testing should not be difficult ...
- You need at least 2 NukkitX servers (ours are hosted at Minehub.de, but that's probably not because of them)
- You need a waterdog server
- Connect these servers to each other (how should I not have to explain xD)
- If everything has been set up correctly, one joins the server system (preferably via cell phone. It also occurs on a PC, but quite rarely. Have not been around for a long time, so it only became apparent later that it wasn't there force happens. However, the Minecraft version was mainly made for mobile phone users. Most users also use it via mobile phone, which is why it is more than annoying)
- Then it doesn't matter whether you stay on the first server or on a second joint. (If you stay on the first one, of course, you only log out once when you disconnect and nowhere else. If you want to join a second one you should actually disconnect the first time, you should go offline twice.)
- The next and last step is simple. Make the server crash so that you can reproduce the error yourself. You do this either by closing the app without logging out, going online with a very weak connection, or by stealing the wifi when you are online!
- don't be surprised if the server doesn't go down the first time. In order to be able to copy the current console edition, I put the server down with two team learners, I was definitely 5 times on until it was ready and the other two 2-3 times.
The team is aware of the error, but luckily not yet. The shot could backfire if it happens ...
-If you want to see what it looks like when +/- 8-15 users are online (unfortunately you can only see the users of the current server in the stream) take a look at the streams with us. In each crash, the server crashes at least once (unless there is a very short stream). There are also streams or general situations where the server goes down several times in succession or sometimes does not want to start again for a while ...
https://www.youtube.com/channel/UCm-ZRmINaO1GIvOQOPaY6zw/videos?view_as=subscriber 

**Screenshots**

German:
Wüsste nicht wofür Screenshots hier nützlich sein könnten. Solltet ihr bestimmte Screenshots brauchen, informiert mich bitte diesbezüglich!
English:
Don't know what screenshots could be useful for. If you need certain screenshots, please let me know!

**Server software used:**

NukkitX oder auch Nukkit

**Additional context**

German:
Ich hoffe das Problem kann behoben werden. Und das am besten, ehe einer der uns ,warum auch immer, vielleicht Schaden will, dass hier liest und unseren Server somit dauerhaft versucht lahm zu legen. In dem Falle wäre ich nämlich wirklich gezwungen Waterdog runter zu nehmen, was ich eigentlich gar nicht möchte. (weshalb ich mich auch bisher mehr oder weniger geweigert hatte, das Problem hier öffentlich anzuschreiben / anzusprechen)
Generell bin ich begeistert von dem System, aber dieses Problem, ist für uns leider keine Kleinigkeit und besteht nun schon ziemlich lange…

Vielleicht könnt ihr es ja in sofern fixen, dass man den Waterdog zwingt auch User auf dem Primären Server (in unserem Fall die Lobby) auszuloggen, in der Hoffnung, dass der Fehler damit schon behoben ist?!? Allerdings kenne ich mich mit Programmieren nicht aus und weiß nicht was für Möglichkeiten ihr da habt…

Auch verstehe ich nicht, warum ich in der Konsolen Übersicht 0/0 stehen sehe, wenn der Server mal wieder gecrasht ist. Ich weiß nur dass es so ist...

Sollten noch fragen sein, stehe ich euch gerne auch über Discord zur Verfügung: DueKay#0624

Liebe Grüße und Danke schon mal,
DueKay
English:
I hope the problem can be fixed. And best of all, before one of us, for whatever reason, may want to harm us by reading here and thus permanently trying to paralyze our server. In that case, I would really be forced to take Waterdog down, which I don't really want. (which is why I had more or less refused to address the problem publicly here)
In general, I am enthusiastic about the system, but this problem is unfortunately not a minor one for us and has been around for a long time now ...

Maybe you can fix it in so far that you force the Waterdog to log out users on the primary server (in our case the lobby), in the hope that the error is already fixed?!? However, I am not familiar with programming and do not know what options you have there ...

I also don't understand why I see 0/0 in the console overview when the server crashes again. I only know that it is ...

Should you still have any questions, please do not hesitate to contact me via Discord: DueKay # 0624

Best regards and thanks in advance,
DueKay

**Comment by Alemiz112** [comment]
Hi. Thanks for this essay!
Usually when player closes game without pressing "Leave Game" button proxy disconnects him due to timeout.
It means that `[10:59:08 WARN]: [/88.153.20.48:46588|DueKay] -> UpstreamBridge - read timed out [10:59:08 INFO]: [DueKay] disconnected with: ReadTimeoutException : null` is normal. 

There are some situations when player keeps disconnected without reason as I mentioned in #98. But I have never noticed that proxy crashes as result of user disconnection.

**Comment by DueKay** [comment]
Abend

Hoffe das es nicht schlimm ist, dass der Text länger geworden ist.

Hab bei dem Beitrag #98 leider zuvor nicht heraus gelesen, dass es das selbe Problem sein könnte.

Hoffe aber sehr, dass es behoben werden kann, und das meine Issuses dabei hilfreich ist


Eve

Hope it is not bad that the text has gotten longer.

Didn't read out about post # 98 that it could be the same problem.

Hope very much that it can be fixed and that my Issuses is helpful

**Comment by TobiasG-DE** [comment]
@DueKay Can you provide us with the logs or can I close this issue due to inactivity?
